-- ~/.config/nvim/lua/plugins/transparent.lua
return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  priority = 1000,
  opts = {
    groups = {
      "Normal",
      "NormalNC",
      "Comment",
      "Constant",
      "Special",
      "Identifier",
      "Statement",
      "PreProc",
      "Type",
      "Underlined",
      "Todo",
      "String",
      "Function",
      "Conditional",
      "Repeat",
      "Operator",
      "Structure",
      "LineNr",
      "NonText",
      "SignColumn",
      "CursorLine",
      "CursorLineNr",
      "StatusLine",
      "StatusLineNC",
      "EndOfBuffer",
    },
    extra_groups = {
      "NormalFloat",
      "NeoTreeNormal",
      "NeoTreeNormalNC",
      "TelescopeNormal",
      "WhichKeyFloat",
      "NoiceCmdlinePopup",
    },
    exclude_groups = {},
  },
}
